name: Node.js CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Asegúrate de usar una versión válida

      - name: Instalar dependencias
        run: npm install  # Cambia 'npm ci' por 'npm install' si no tienes package-lock.json

      - name: Ejecutar pruebas
        run: npm test
